config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # All
  get '/tasks', to: 'tasks#index'

  # Show
  get 'tasks/:id', to: 'tasks#show', as: 'task'

  # Create
  get 'tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'

  # Update
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'tasks_edit'
  patch 'tasks/:id', to: 'tasks#update'

  # Delete
  delete 'tasks/:id', to: 'tasks#destroy', as: 'tasks_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :create, :update, :edit, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    # @task = Task.new(params[:task])
    @task.save

    redirect_to task_path(@task)
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <div>
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <br>
  <%= f.label :details, "Details" %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit task: <%= @task.title %></h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
  <li><%= link_to task.title, task_path(task) %> - <%= task.details %></li>
  <% end %>
</ul>

<h4><%= link_to "Add a new Task", tasks_new_path%></h4>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form', task: @task %>

<br>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>


<%= link_to "Delete restaurant", task_path(@task), method: :delete, data: { confirm: "Are you sure?" }  %>

<br>


<%= link_to "Edit task", tasks_edit_path %>

<br>

<p>-------------------------------------</p>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>

<p>Find me in app/views/tasks/update.html.erb</p>